# use node:22.9.0
FROM node:22.9.0

WORKDIR /frontend

# Copy everything from frontend folder
COPY . .

# Install dependencies
RUN npm install

# Build the frontend
RUN npm run build

# Expose port 3000
EXPOSE 3000

RUN ls -a

CMD ["npm", "run", "start"]
